language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  api_key:
    secure: MV69E3auwtc17AHFRgMSXcp/kyrO7jehgEift8cjYDhGvyhIzqvWAQO4gcZoM7DeSdv448DMmrMMfXO1VOUnb2RC5+byHdAkLii6brpZVkseimMxZgxMNFw6n2kfBRbvP3vilpxQLEX06HqqKs/malQTPMoYnQgvPC6/pdGcajVlIWb35x9x97yMWfwS6GLAzlvPVr7z9f3Z2ZSYMTcXQXU/wpZgLSZ6SzWJ8gME+9qRlCzBlJymwZ/IcvK/BXwHyzPdxJwR95WU80hFgWWW0I/zgrOiD61dAACxuCpVyOstpb501FsdVc9Z6SUrygy4ypsQF4U0JCLioxR4vwnPfQUgb84jhRmT9r6r96owhOmYONcyfNH52xynbK/8byPmcVyrGMme2CwPr8IOySqniGrrvYExehk0Syi1/neKsg5Ba56CssGS1ZBQEUfMV3lOFT01o1xhalgllix2drN5np/fLS3LB4eBh/DzA6G8kqi1FzX7oL5hP+FPy8/wmvhj2TcC8PYw/O7UC+FgeAq7SFD14yZ1vVMf11TZl8BWLdwpPyI1iIGy776a8JnndOXmqHdVLKyQ2HLKDE+bE97q0vY45ki1+CQ5hzLlKBuRchzAip9/BKX3GNSmgOAn5KuYLrlFjnI+K5FlMElpmxMZQU4vmwntKLLNzf3JXQhWWZA=
  app: taigirquote
  on:
    repo: hdushan/taigirquote
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
