language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  api_key:
    secure: IG1b8h7cZ3MSaZ2mubI9fjrg9IfNX6ePhvkWB927S1/i7D1PrLRveOqX4/5nJsOOu6dOpR3WyDY5EyaPgSXxOkcZF0bfXqWnueR1quVRbJa/I3NMeIic/gEUXm/K00lRz9UBEa+oT3CH6yKKFo1MOVRrDBHlHUeptc6jrocmgx1ZWQdAMgclIUWpsAuFerPbnq3ccFaHcTCNjV3kLghh1nM7C2NbK6w6TKmvrXNVKwjEOxIcWIuOQ1dGLVRvGiJCxIHWP3Q5ANf3NEF8I8LCiEVp0TqPJv2EJLmvxa6KyWu3qiFeh7vs5PAOg0re5DL9qdA3rpZk3hSvRVbUKK5ZIDpyG4kO3bnuHX5MFo6hoSkOt4HGD0JVBksDDN1VyjaC2yLqWpcxVUbV/avNc21sb+BqJ9NHUfMU95fcs2RvEPZJ4+DHJn4BAFSwN/7yXf9OhXb+Kb/qVre/sLHb2XuV1+XdUhX0LvrWTScqeEyzBh+zF4wKPQuE8B4i4M4ppmZBjDI+SelzZ+7Qamam9zPXUM3ht+qa5A6C0x4G9SirC55/7TAgR2ZlfiWkrocw8aXGJ1DOgcowH7o/AmaUV8GGZtOonBvwyQN11coEeWxvhIRwOT39TxrSJ5Y/fZjxJSDmWQRo/OQVECi8fnio5Tr4goHzKIH2G9HesgCs6P8GD9c=
  app: taigirquote
  on:
    repo: hdushan/taigirquote
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
