language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  api_key:
    secure: vbDsOcA7DipjpNt8B0ieKBmScqTHagJe13KvWo6ilUtW+gjpRpEMEll/mi4aDqwzBRym/guSzKrNYM4XEDqK4csb4xp0QPXXTx9fVInKW8Xhzdatvbc4R5tTbCexStxK5nb4j06JDJWEMA0v+2RoH3LmeiZmWhjT6e3heIsYl2IdJ6EQ8oiGy0yL/y2ui7R7v02C4PsoRVKoKpeNglutYpOKVjiFNunBulbhLC4bCzIrLMhvHTJyTtSkuY66Xr2uFt43EFL/U2hYQblcus5WVdECODcBSXpWYXlEe1SA71SbEhL7WJb5QeIzai5xAKHYljzs/hQrz+wK5BcKMybbZ4oaHUIgqjaApbLCxmdBio3xnloiZZUhONUm+hheu5nWiW0OdBiYWXQhObj5FikXqdf6S8ELG/sCFXQwJARaSJlYJSF/PeVpGW5ENGqvTeBO5ElYQ4ydTuHSPNvT+B8UJp/OyfFdJ8wnXvRNLB3mtE+DJtfhZHDoJPKFTeaF9xTIU72zU/7XHKkhDpv80RhvJ9auveqCBka4VbiIp1PAoiyHn6BKnn6ZHcui7ebvahOhx7518e/XwMXdPaRd94Q9lCI3KicerCDXyZS20+VPItzPunSiWz2ljgFZc4TokCdwOKt376cfypPevnkMOql7yVRbwT0g0DlvhjokUUiOGz8=
  app: tagirquote
  on:
    repo: hdushan/taigirquote
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
