language: ruby
rvm: 2.2.3
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
deploy:
  provider: heroku
  api_key:
    secure: NXPT3Q38+r4OzrF+H8uTv9jixEno53ayssibsE0z1HeqdVN8uXhf9xRF+5v35CrUq/d5waFCmp9ZVTdbY/GSJF06gcDYLhurQglG9ZM4UaWpUJKx9unrsLf/Msrdd0gs9CWe2sAjqMTNLbC/7qXqiYFqYBOBSbB4BGfF7hqa0bamHWXzG7ZAqaxQt9Tt6FBknQriZAwN04TSm+9o44xjRdRU29+WC4NjlWpL1kf/BWwS8NBZaAsB/KW0CbVaK2vj5uCQ1UTx0xtZJsUFBlcR7hlLpOG7Gz9k5a/VUU08JYYZPyLqBzG1fAK5uxPHtYMSKU5coy82VSAlM0S/pLZkaQEaCAcjTJkjsg1A/AjnEfHw3whrrFKkxFWGvRMIcLsWjeUphEGmRld54Nbe3t732SV7W14FvXCZmQZ4Fljn/AkFOwG+WPpCfs2MZiJuJCLV0iDisldfTXhFNVsv8AHZyiFurmog8aN5V6CFxG0sGFUfVMVhvA8cYMUN3AKj6iLMb9269lpssRQOtN1d3atMFaJODZlU1mucp3DHWvkUt/D59OO20JOw779ZEC4FzMCke5VRAJf9v8uW2sTWwjOZsGzhtDs9NJUJSygb7+k0Ei//dtfxMkka/VZItiObDsYn4fpbFw77SayIBhdTPsyMpHKcxuBPmE/dtmKnnRuinrc=
  app: taigirquote
  on:
    repo: hdushan/taigirquote
notifications:
  email:
    recipients:
    - hansrd_98@yahoo.com
